// Mocks generated by Mockito 5.4.6 from annotations
// in learn_riverpod/test/core/services/app_request_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:learn_riverpod/core/services/app_logger.dart' as _i2;
import 'package:learn_riverpod/core/services/network_connectivity.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i2.AppLogger {
  @override
  dynamic debug(String? msg, {dynamic data}) => super.noSuchMethod(
    Invocation.method(#debug, [msg], {#data: data}),
    returnValueForMissingStub: null,
  );

  @override
  dynamic error(String? msg, {dynamic data}) => super.noSuchMethod(
    Invocation.method(#error, [msg], {#data: data}),
    returnValueForMissingStub: null,
  );

  @override
  dynamic info(String? msg, {dynamic data}) => super.noSuchMethod(
    Invocation.method(#info, [msg], {#data: data}),
    returnValueForMissingStub: null,
  );

  @override
  dynamic warning(String? msg, {dynamic data}) => super.noSuchMethod(
    Invocation.method(#warning, [msg], {#data: data}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnectivity extends _i1.Mock
    implements _i3.NetworkConnectivity {
  @override
  _i4.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
